run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: false
    disable:
      - shadow
    enable:
      - printf
      - structtag
      - unreachable
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - govet

    # Exclude known false positives
    - text: "should have a package comment"
      linters:
        - revive
